infinitered/ignite-bowser

readme.md
screenExamples.js

This updates the README with a rough first version of Bowser-specific content. We should refine this later, but this get's it at least referencing reality. 
The screen examples were leftover from Andross and were throwing errors on, so I also removed those.

Update README with Bowser directory structure, fix plugin examples

---

boilerplate/src/models/navigation-store/navigation-store.ts

We need to actually dispatch the `fireSubscribers` from NavigationEvents in order for navigation's `addListener` to work.
```
const fireSubscribers = (action: any, oldState: any, newState: any) => {
// tell each subscriber out this
subs.forEach(subscriber => {
subscriber({
type: "action",
action,
state: newState,
lastState: oldState,
})
})
}
```
in `navigation-events.ts` - this wasn't included in the NavigationStore `dispatch` action :doh:

Dispatch fireSubscribers in NavigationStore

---

boilerplate/package.json.ejs

- Issue #19 (puppeteer is now a dependency)
- Added a customized `@storybook/addon-storyshots` without `puppeteer` dependency
- Repo: https://github.com/infinitered/addon-storyshots

Add: @storybook/addon-storyshots without puppeteer dependency

---

boilerplate/package.json.ejs
boilerplate/src/app/main.tsx.ejs
boilerplate/src/views/shared/button/button.story.tsx
boilerplate/src/views/shared/checkbox/checkbox.story.tsx
boilerplate/src/views/shared/form-row/form-row.story.tsx
boilerplate/src/views/shared/header/header.story.tsx
boilerplate/src/views/shared/icon/icon.story.tsx
boilerplate/src/views/shared/switch/switch.story.tsx
boilerplate/src/views/shared/text-field/text-field.story.tsx
boilerplate/src/views/shared/text/text.story.tsx
boilerplate/src/views/shared/wallpaper/wallpaper.story.tsx
boilerplate/storybook/storybook.ts
boilerplate/storybook/storybook.tsx
templates/component.story.tsx.ejs

- Issue #32 (Hot reloading on storybook is not working)
- `storiesOf()` takes a second parameter so I've added it.
- FIXED ~~(WIP) Unlike the generated app, hot reloading doesn't work on storybook.~~
- It reloads but doesn't refresh. It works when enabling `Live Reloading`, of course. It's just not hot.
- https://github.com/bvic23/babel-plugin-functional-hmr looked promising so I gave it a shot but didn't work
- Refs:
- https://github.com/facebook/react-native/issues/10991
- https://github.com/storybooks/storybook/issues/2081
- Added a root component for StorybookUI since RN hot module must be in a class for HMR
- Hot reloading example (GIF):

Fix hot reloading on storybook

---

commands/screen.js
package-lock.json
package.json
templates/screen.ejs
test/generators-integration.test.js

This just polishes up the screen generator that was already in place. [Trello](https://trello.com/c/b5mKF4a5/1-screen-generator-25)
Changes include:
- camelCase instead of pascalCase for the entry in AppNavigator
- `--folder` or `--f` option which allows for easier integration tests (shamelessly stole this code from @carlinisaacson )
- Conditional imports for `Text` `Screen` and `color` since they're imported from different places depending on where the user placed the screen
- camelCase instead of pascalCase in `i18n` translation string
- Added a basic `ROOT` style

Polish screen generator

---

boilerplate.js

- Support `sed` command for non-MacOS while setting up splash screen by separating backup extension parameter
- For the reviewers: Since you guys reviewed the splash screen PR, I'm adding you. Thanks!

Fix: support sed command for non-MacOS

---

boilerplate.js

Since there are a couple of issues that make the generated project messy, we need to block this until the issues are solved.

HOLD: installing splash screen

---

boilerplate/package.json.ejs

There's a breaking change somewhere between 2.0.4 and 2.3.... this buys us time while we dig in.

📌 pins react-navigation until we have time to figure it out

---

boilerplate.js

- Task: https://trello.com/c/uSt9ti2S/19-25-splash-screen-issues
- This should fix:
- #40 - Error: Command failed: sed -i '' while creating new project
- #42 - Splash screen linking issue on android
- There's no problem running on iOS but having and issue on Android when running it with `react-native run-android`. It seems like my npm environment causes it(https://github.com/react-community/create-react-native-app/issues/603) @skellock @ryanlntn Could you guys test this branch?

Fix: splash screen issues by pinning version

---

boilerplate.js
boilerplate/package.json.ejs
boilerplate/patches/splash-screen/splash-screen.patch
boilerplate/storybook/storybook.tsx
package.json

- Moved `react-native-splash-screen` to `package.json.ejs`
- Hide splash screen as soon as root component is mounted since it's the first action (kind of). This will fix #54, https://github.com/infinitered/ignite/issues/1287
- Increased version to apply the latest changes
- Let me merge this first to confirm above fixes are applied and working. Please review although. Thanks!

Splash in boilerplate package

---

boilerplate/README.md

https://trello.com/c/rI1tF8Ls/24-add-storybook-instructions-to-default-readmemd
Adds instructions to the generated README file about how to run Storybook.

Add storybook instructions to README

---

boilerplate/package.json.ejs
boilerplate/src/i18n/en.json
boilerplate/src/theme/color.ts
boilerplate/src/views/shared/form-row/form-row.story.tsx
boilerplate/src/views/shared/header/header.story.tsx
boilerplate/src/views/shared/text/text.story.tsx
boilerplate/storybook/storybook.tsx
boilerplate/test/__snapshots__/storyshots.test.ts.snap
boilerplate/test/mock-textinput.ts
boilerplate/test/setup.ts

New Trello Board link: https://trello.com/c/YPZKngqg/28-configure-reactotron-in-storybook
Closes https://github.com/infinitered/ignite-ir-boilerplate-bowser/pull/81
Implements add-reactotron-to-storybook based on Kevin's suggestion in https://github.com/infinitered/ignite-ir-boilerplate-bowser/pull/81
Reactotron now executes when running storybook tests. It shuts off as expected when running `yarn test`.
This PR fixes this  test warning:
"console.warn node_modules/react-native/jest/setup.js:91
Calling .blur() in the test renderer environment is not supported. Instead, mock out your components that use findNodeHandle with replacements that don't rely on the native environment."
by adding a new mock for text-input "mock-textinput.ts" that sets the "autoFocus" prop to false when tests are …

Add reactotron to storybook

---

boilerplate/src/services/api/api-config.ts
boilerplate/src/services/api/api.ts
boilerplate/src/services/api/api.types.ts
boilerplate/src/views/example/second-example-screen/second-example-screen.tsx

This is for #92 
Quote for convenience:
"Github has a really great, robust REST API.
However, it doesn't feel like it makes the most ideal example API for Ignite.
- Repos aren't super relatable as a data type, compared to, say, users
- It has some custom configuration, like it's custom Content-Type: application/vnd.github.v3+json which can be confusing if you're trying to transform our example into your own API service .
I'm proposing switching the sample API to https://jsonplaceholder.typicode.com/, which is designed to be a sample, and supports straight REST endpoints for data types like users, todos, posts and other familiar example concepts."

Switch example API to from GitHub to Typicode JSON example api

---

boilerplate/package.json.ejs
boilerplate/src/navigation/navigation-events.ts
boilerplate/src/navigation/navigation-store.ts
boilerplate/src/navigation/stateful-navigator.tsx

Hi guys !
I have updated the React-Navigation to 2.3.1 and did some changes based on the `react-navigation-redux-helpers`
Thanks 👍

Support React-Navigation v2.3

---

boilerplate/src/services/reactotron/reactotron.ts

With a newly-generated project, typescript was complaining about `src/services/reactotron/reactotron.ts`:
```
Type '{ configure: () => any; connect: () => any; use: () => any; useReactNative: () => any; clear: () => any; log: () => any; logImportant: () => any; display: () => any; error: () => any; image: () => any; reportError: () => any; }' is not assignable to type 'Reactotron'.
Property 'close' is missing in type '{ configure: () => any; connect: () => any; use: () => any; useReactNative: () => any; clear: () => any; log: () => any; logImportant: () => any; display: () => any; error: () => any; image: () => any; reportError: () => any; }'.
```
Once I added `close`, it complained about `warn`, then `benchmark`, so I added those too.
I also sorted the list, because I’m OCD that way.

Add a few more Reactotron mocks, to make Typescript happier

---

boilerplate/src/lib/storage/storage.ts

If you call `storage.save("someKey", 1)` on iOS -- you'll get a runtime exception about an unrecognized selector being thrown while `invoking multiSet on target AsyncLocalStorage with params (...`.
`AsyncStorage.setItem()` can only take string values -- the existing check of `typeof === 'object'` will return `false` if you try it with a number, and then `AsyncStorage.setItem()` will be called with the number argument, which is what causes this exception.
It's safe to call `JSON.stringify` on numbers and strings -- it'll always return a serialized string, so we can sidestep this issue completely.

Always stringify value before passing to `AsyncStorage.setItem()` in `storage.save`

---

boilerplate.js

Fixes: https://github.com/infinitered/ignite-ir-boilerplate-bowser/issues/120
We are calling `react-native link` with spawn on [line 166](https://github.com/infinitered/ignite-ir-boilerplate-bowser/blob/ce622b781c83e4e0a479714fc83afcc0dd492e1d/boilerplate.js#L166). Calling it the second time with spawn fixes the maximum call stack size exceeded error.

Call react-native link with spawn instead of run

---

boilerplate/package.json.ejs

npm-run-all 4.1.3 depends indirectly on flatmap-stream, which has been yanked
from npm because it contained malicious code:
https://www.npmjs.com/advisories/737
https://github.com/mysticatea/npm-run-all/issues/149

Bump npm-run-all version for security

---

boilerplate/package.json.ejs

Ref: https://github.com/facebook/react-native/issues/22863

fix: Lock react-devtools-core to 3.4.3 to avoid issue with 3.5.0

---

boilerplate/src/services/api/api-problem.test.ts
boilerplate/src/services/api/api-problem.ts
test/generators-integration.test.js

My project’s API started 404ing today, causing me to notice that the boilerplate `getGeneralApiProblem()` doesn’t correctly translate 404 errors.
I added a test for all of its translations, made the test pass, and copied the test to this project… and noticed that we don’t have a test that ensures that new apps’ tests pass, so I added that too. (Surprisingly, it doesn’t seem to add to the test time, because of jest’s parallelism? — tests still take about 320s on my machine. 🎉 )

Fix api-problem's translation of 404 errors

---

.circleci/config.yml
boilerplate.js
boilerplate/.babelrc
boilerplate/app/screens/first-example-screen/first-example-screen.tsx.ejs
boilerplate/app/screens/second-example-screen/second-example-screen.tsx.ejs
boilerplate/e2e/README.md
boilerplate/e2e/config.json
boilerplate/e2e/firstTest.spec.js
boilerplate/e2e/init.js
boilerplate/package.json.ejs
package.json
test/generators-integration.test.js

This adds the option for the user to include Detox end-to-end tests with their Ignited app.
They will have to install some additional dependencies in order to run the tests, but I've included a specific README to go over what they need to do. They are pointed towards this README during the Ignite process after they say yes to Detox. 
I've also added a job to the CI workflow that ignites an app with Detox and ensures that the Detox tests pass. 
If you'd like to skip the question when Igniting (so you can run it and forget it without waiting for the prompt) you can use `--detox` or `--no-detox`.

Add optional Detox end-to-end tests

---

boilerplate/app/components/button/button.story.tsx
boilerplate/app/components/checkbox/checkbox.story.tsx
boilerplate/app/components/form-row/form-row.story.tsx
boilerplate/app/components/header/header.story.tsx
boilerplate/app/components/icon/icon.story.tsx
boilerplate/app/components/switch/switch.story.tsx
boilerplate/app/components/text-field/text-field.story.tsx
boilerplate/app/components/text/text.story.tsx
boilerplate/app/components/wallpaper/wallpaper.story.tsx
templates/component.story.tsx.ejs

The Storybook fix for this issue https://github.com/storybooks/storybook/pull/1525
adds a warning when `storiesOf` doesn’t have a `module` parameter. This leads to warnings during the storyshots test for each of the provided Bowser components:
```
PASS  test/storyshots.test.ts (8.026s)
● Console
console.warn node_modules/@storybook/client-logger/dist/index.js:13
Missing 'module' parameter for story with a kind of 'Text'. It will break your HMR
console.warn node_modules/@storybook/client-logger/dist/index.js:13
Missing 'module' parameter for story with a kind of 'Button'. It will break your HMR
[...]
```
Any components generated with `ignite generate component` will also trigger this warning.
The `module` parameter is necessary to enable hot-module-replacement to work right: …

Quell storybook HMR warnings

---

commands/generate/navigator.js
commands/generate/screen.js
lib/patterns.js
templates/navigator.ejs

- adds a navigator option for the generator command
- adds a template for a navigator
- fixes patching call in screen generator
[![](http://yulolimum-monosnap.s3-website-us-west-2.amazonaws.com/assets/static/placeholder.video.jpeg)](http://yulolimum-monosnap.s3-website-us-west-2.amazonaws.com/uploads/20190312_6j2vd.mp4)

Adds a navigator generator for react-navigation.

---

boilerplate/app/models/root-store/root-store.ts
boilerplate/app/navigation/navigation-store.ts
boilerplate/package.json.ejs
templates/model.ejs

According to changelog: MST 3 is twice as fast in initializing trees with half the memory consumption compared to version 2
https://github.com/mobxjs/mobx-state-tree/blob/master/changelog.md
I couldn't update mobx to 5.9.4 due to iOS 9 doesn't support proxy (I learned it hard way).

change(mobx): Update to mobx-state-tree version 3.12.2

---

boilerplate/app/i18n/i18n.ts
boilerplate/package.json.ejs
boilerplate/test/mock-react-native-languages.ts
boilerplate/test/mock-react-native-localize.ts
boilerplate/test/setup.ts

`react-native-languages` was renamed to `react-native-localize` (https://github.com/react-native-community/react-native-localize/pull/29)

change(i18n): Migrate to react-native-localize

---

boilerplate/app/navigation/navigation-store.ts

Addresses #84 
Prevents crashes when rehydrating state stored before making changes to routes (e.g. renaming a route).

Add preProcessSnapshot to NavigationStore 

---

boilerplate/app/components/text/text.props.ts
boilerplate/app/components/text/text.tsx
boilerplate/app/i18n/translate.ts

* Removes `translateWithVars` function in favor of adding optional options argument to `translate`
* Updates Text with `txOptions` prop to pass options to translate (resolves #83)
* More info regarding translate options here: https://github.com/fnando/i18n-js#setting-up

Add txOptions prop to Text to pass options through to translate

---

readme.md

- Fix Markdown link syntax by adding forgotten `[` character

docs: fix Markdown link syntax

---

boilerplate/app/components/button/button.story.tsx
boilerplate/app/components/header/header.story.tsx
boilerplate/app/components/text-field/text-field.story.tsx

fix: Replace window.alert with Alert.alert

---

boilerplate/package.json.ejs

Per our conversation on Slack this removes jest-preset-ignite in favor of handling jest configuration in the bowser boilerplate package.json.

Remove jest preset ignite

---

readme.md

This adds an explanation of our decision to choose MobX State Tree and Typescript for the Bowser stack. 
Please proofread! I'm notorious for typos 🤦‍♀

Add stack justification to README

---

commands/generate/model.js

Fixes #222 
Insertions needed a few newlines and a corrected `after` property.

Fix root-store insertions for store model generator

---

boilerplate.js
boilerplate/.solidarity
boilerplate/package.json.ejs
test/generators-integration.test.js

When I try to generate a new project and run tests, they fail with `Cannot find module 'emotion-theming' from 'index.js'` which seems to be [this Storybook problem]( https://github.com/storybookjs/storybook/issues/5817) -- it seems like a couple of their dependencies aren't being hoisted properly, and seems to be fixed by explicitly adding them to the main project... which I've done.
Also, fixed #231 - don't run `pod install` unless the `pod` executable is available. Also, I added a Solidarity rule to check for that executable on Mac only.
Also also, fixed #199 (at least, the part I think is actionable) -- the generated-app test now explicitly verifies that `yarn compile` doesn't complain (along with the existing format & lint checks).

Fix storybook dependency problem (and a couple of others)

---

commands/generate/navigator.js
test/generators-integration.test.js

`ignite g navigation Test` failed with a type error: `read-pkg-up` doesn't return the package; it returns an object with {package, path}. (I did bump the `read-pkg-up` version from 5.0.0 to 6.0.0 recently, but it's not apparent from the limited release notes that the result type changed... so maybe this has been broken for a while.)
Fixes https://github.com/infinitered/ignite-bowser/issues/237.
Also added a simple test for the navigation generator. To drive the generator from the test, the generator now checks for options before asking its questions. Like the other generator tests, this one isn't exhaustive, but at least checks that the basic flow works, which'll hopefully prevent problems like this in the future.

Fix navigation generator

---

boilerplate.js
boilerplate/bin/postInstall

This is an alternative to #245, which I think will work better for the long term.
This adds a new `bin/postInstall` script to do all the yarn or npm postInstall steps; it can be
smarter about what steps to run on which platforms, more generally than #245 did.
I've also added a new postInstall step: it kills any running instance of the Metro bundler when you install packages. I've had problems when I forget to do this, and it takes virtually no time. Note that it only does this on Mac or Linux because I haven't worked out the equivalent Windows incantation; HELP WANTED if a Windows person wants to try!
I've tested `ignite new MyApp -b ./bowser` on Mac and Windows.
Like the other implementation, this should fix #243 and maybe #244.

Move postInstall commands to their own script; add command to kill metro

---

boilerplate.js

When trying to start a new project on Windows, I was getting an error:
```
Error: Command failed: yarn
'.\bin\postInstall' is not recognized as an internal or external command, operable program or batch file.
```
This should fix that. Tested on Windows and is working.
Related: #243 #247

Fix windows postInstall issue

---

boilerplate/app/models/extensions/with-environment.ts
boilerplate/app/models/extensions/with-root-store.ts
boilerplate/app/models/extensions/with-status.ts
boilerplate/app/models/root-store/root-store.ts

Interfaces support recursion a little better than types.

Fix "Type alias 'RootStoreType' circularly references itself"

---

boilerplate/app/navigation/back-button-handler.tsx
boilerplate/app/navigation/stateful-navigator.tsx
boilerplate/package.json.ejs
readme.md
templates/screen.ejs

Considering we've migrated to hooks, it makes sense to me to move to [mobx-react-lite](https://github.com/mobxjs/mobx-react-lite) which describes itself as the following:
> This is a next iteration of mobx-react coming from introducing React hooks which simplifies a lot of internal workings of this package.
Tested with master branch:

feat(mobx-react): swap out mobx-react for mobx-react-lite

---

readme.md

I tried scaffolding new Bowser project (v4.7.4) but I always go an error saying `failed to add React Native 0.61.2` and I couldn't get pass that no matter what I tried.
After searching and trying some things I found about Ignite CLI `--debug` option where I saw that I got an error saying I'm missing CocoaPods and after I installed CocoaPods I managed to get project scaffolded without any problems.
Relates to #250

chore(docs): Added CocoaPods note

---

boilerplate/app/components/text/text.story.tsx
boilerplate/test/__snapshots__/storyshots.test.ts.snap
boilerplate/test/i18n.test.ts

This adds a test that greps for missing i18n keys. 
The grep will match any of the following:
- `tx="foo.thing"`
- `rightTx="foo.thing"`
- `translate("foo.thing")`
It does not cover translation keys that are passed in as a variable, but it should cover 95% of cases.

Add test for missing i18n keys

---

boilerplate/test/i18n.test.ts
boilerplate/tsconfig.json
package.json
src/boilerplate.ts
test/generators-integration.test.ts

I noticed that a new app would redscreen with an error about not being able to find the Montserrat font, and traced the problem to Bowser's attempt to `react-native link` when I didn't have the `react-native` package installed globally anymore (as recommended under "Creating a new application [in the RN Getting Started doc](https://facebook.github.io/react-native/docs/getting-started.html)).
To fix this problem, I prefixed the link command with `npx`; Ignite itself was already updated to do this, but Bowser hadn't been updated to match.
To help expose problems like this in the future, I changed the link command to use `exec` instead of `spawn`: `exec` will raise an exception on failure, where we'd need to examine the `spawn` result (two different ways!) to detect an error. Looking around, …

Fix `react-native link` to use npx; use `exec` instead of `spawn` to catch failures

---

boilerplate/app/app.tsx.ejs
boilerplate/app/i18n/i18n.ts.ejs
boilerplate/app/navigation/primary-navigator.ts
boilerplate/app/navigation/root-navigator.ts
boilerplate/app/services/reactotron/reactotron.ts.ejs
boilerplate/app/theme/fonts/index.ts
boilerplate/app/utils/storage/storage.ts.ejs
boilerplate/index.js.ejs
boilerplate/package.json.ejs
src/boilerplate.ts

Tested by creating an RN version and an Expo version, both works fine.
- i18n: `expo-localization`
- Fonts: `expo-font`
- AsyncStorage: Since Expo hasn't brought in the community version yet, we need to use RN version for now even though it's deprecated.
- Keychain: Expo uses its own `expo-secure-store`. Need to employ it.

Expo compatibility

---

readme.md

The SSL URL https://community.infinite.red/ is not working, update readme to use http://community.infinite.red/

Fix Readme Broken links

---

boilerplate/index.js.ejs
src/boilerplate.ts

- Expo needs `react-native-safe-area-context` which depends on `react-native-safe-area-view`
- `react-navigation-stack` was updated 3 hours ago, requires `@react-native-community/masked-view`

Update deps for Expo

---

src/boilerplate.ts

This will allow for `npx ignite-cli new <foo>` with Bowser without erroring because ignite isn't installed globally.

Switch to npx ignite-cli when ignite not available globally

---

src/boilerplate.ts

React Native has required cocoapods to be installed since 0.60 (when not using Expo); per https://github.com/infinitered/ignite/issues/1548, the outcome isn't optimal, so let's explicitly check for `pod` and print a clearer error message in that situation.

Verify cocoapods is installed, if RN >= 0.60 and not Expo

---

templates/screen.ejs

uncommenting the line `const { someStore } = useStores()` in a newly created project gives an unintuitive **TypeError**.  
I understand that the use of rootStore may be discouraged, but it may be useful for beginners at least to add a line that works as is when uncommented.
By the way, are 3 lines too much?

Fix screen template: useStores() comments

---

boilerplate/README.md

The SHOW_STORYBOOK variable is located in `index.js`, not `app/app.tsx` 🙂

Fix Storybook instructions in README.md

---

src/commands/generate/model.ts

Fixes https://github.com/infinitered/ignite-bowser/issues/344

Fix rootStore import path for generate store model

---

boilerplate/package.json.ejs

Seems in the `package.json` file we were asking for `@react-native-community/async-storage` twice. This removes the duplication and upgrades the module to `^1.11.0`

Removes duplicate @react-native-community/async-storage

---

templates/styles.ts.ejs

This fixes a bug when generating components:
**Steps to reproduce:** 
- Follow the steps at https://github.com/infinitered/ignite in the "Use Ignite Bowser" section, using defaults throughout.
- Run "react-native start" 
- react-native run-android
**Result:** 
"error: Error: Unable to resolve module `../theme` from `app/components/pizza-location/pizza-location.styles.ts`"

Fixed template path bug.

---

boilerplate/app/utils/ignore-warnings.ts
boilerplate/package.json.ejs
boilerplate/storybook/views/use-case.tsx

I tested @nirre7's #362 PR and noticed that (as usual) some dependencies could be bumped with it.
Tested for both --expo and --no-expo; only tested with --no-detox, though.

Bump dependencies (merge AFTER the 0.63 bump)

---

boilerplate/app/utils/ignore-warnings.ts.ejs
boilerplate/package.json.ejs
src/boilerplate.ts

Fixes an error introduced in Bowser 5.3 when using Expo. 
More details: https://github.com/infinitered/ignite-bowser/issues/367 
The following changes makes the boilerplate work again with and without Expo.
|  | React Native | Expo |  Comment |
| --------------- | --------------- | --------------- | --------------- |
| @types/react-native | 0.63.2 | 0.61.23 | |
| react-native | 0.63.2 | 0.62 | https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz |
| LogBox | Yes | No | |
| YellowBox | No | Yes | |

Fix #367 - Use YellowBox with Expo

---

boilerplate/README.md.ejs
boilerplate/package.json.ejs
boilerplate/tsconfig.json.ejs
src/boilerplate.ts

After adding support for Expo, some files still contains code that shouldn't be there. This PR makes sure an Expo app will get the correct references.

Close #370 - Update references when using Expo

---

boilerplate/README.md.ejs
boilerplate/app/screens/welcome-screen/welcome-screen.tsx.ejs
boilerplate/bin/downloadExpoApp.sh
boilerplate/e2e/README.md.ejs
boilerplate/e2e/firstTest.spec.ejs
boilerplate/package.json.ejs
src/boilerplate.ts

Added detox e2e tests for Expo projects. [only iOS]  
Fixes https://github.com/infinitered/ignite-bowser/pull/299
I have made least amount of changes to get it working. 
One thing i want to mention though, the latest version of detox specifically checks for the visibility of the element and on the welcome screen `welcome-screen.tsx`, the `Continue` button at the bottom was being hidden by the `LogBox` popup that appears after the app opens, giving the following error
```
Test Failed: View “<RCTView: 0x7fa08ded38f0>” is not visible: view does not pass visibility threshold (75%)
TIP: To print view hierarchy on failed actions/matches, use loglevel verbose and above.
```
So i have added some `marginBottom` to make the button properly visible as in the below image
`const FOOTER: ViewStyle = { …

Added detox e2e testing for Expo apps

---

readme.md

Grammar pass
