infinitered/ignite-bowser

- boilerplate/src/views/example/second-example-screen/second-example-screen.tsx
I think it's better to use the InfiniteRed avatar instead of the Gant avatar.  😆 
I also added a few more things to the `.display()` call to show a little more.
> 💄 Switches to the Infinite Red brand

- commands/screen.js
- templates/screen.ejs
> code fixes on the generated templates on generate screen command

- commands/screen.js
- package-lock.json
- templates/component.presets.ts.ejs
- templates/component.story.tsx.ejs
- templates/component.tsx.ejs
Will fix https://github.com/infinitered/ignite/issues/1268 when released.
> Fix broken generated component paths

- boilerplate/package.json.ejs
Per discussion here: https://github.com/infinitered/ignite-ir-boilerplate-andross/issues/120
Removes husky, lint-staged, and precommit script from package.json
> Remove husky, lint-staged, and precommit from package.json

- commands/model.js
- ignite.json
- templates/model.ejs
- templates/model.test.ejs
Adds a simple model generator to generate a propless mobx-state-tree model and test.
> Simple model generator

- boilerplate/README.md
- readme.md
Replaces old Andross readme with new readme from this boilerplate's root.
> Update boilerplate readme

- boilerplate/storybook/storybook.tsx
- Issue #49
- Thanks to @juddey for reporting the issue and posting the solution.
> Fix: hide splash screen when running storybook

- boilerplate.js
> Fix: linking node modules

- boilerplate.js
- https://github.com/infinitered/ignite-ir-boilerplate-bowser/issues/61
- https://github.com/infinitered/ignite-ir-boilerplate-bowser/issues/62
- https://github.com/infinitered/ignite-ir-boilerplate-bowser/pull/66
> Replace sed command to plain JS / fixed camelcase android path

- boilerplate/src/navigation/stateful-navigator.tsx
🔥 🔥 🔥 🔥 🔥
You semicolon hating monsters! Anyway, there you go.
> Remove unused import and update path

- boilerplate/src/app/root-component.tsx
> Fix typo and fix import path

- boilerplate/package.json.ejs
We were running on the older beta here.  Let's get this updated to the latest & greatest.
> ⬆️ upgrades reactotron to latest version

- boilerplate/src/app/setup-root-store.ts
Pretty self explanatory. It would be nice for rehydration to not fail completely silently. Helps shorten that feedback loop.
> Log rehydration errors to reactotron

- commands/component.js
- commands/model.js
- commands/screen.js
- lib/domains.js
- package-lock.json
- package.json
- test/domains.test.js
- test/generators-integration.test.js
Fixes #36 
Extract domain handling logic into it's own module. I also fixed up a few issues I discovered with the model generator in the process.
> Dry up domains

- templates/screen.ejs
> Remove duplicate “Screen” in screen template

- commands/screen.js
> Add friendly message when users include `-screen` suffix

- templates/model.ejs
> Add postProcess hint to model generator

- boilerplate.js
- boilerplate/package.json.ejs
- lib/react-native-version.js
react-native => 0.57.7
react-navigation => 3.0.0
> bumped react-native & react-navigation

- boilerplate/package.json.ejs
Reference: https://www.npmjs.com/package/@types/validate.js
Fix for https://github.com/infinitered/ignite-bowser/issues/135
> [@types/validate.js] Remove deprecated library

- boilerplate.js
- boilerplate/bin/setup
Fixes #143
* Not sure if anything else is needed.
* I removed some lines from the example script that I don't think are relevant.
* Tested running script
> Add setup script

- boilerplate/app/utils/validate.ts
> Cast for TypeScript

- boilerplate.js
This should fix https://github.com/infinitered/ignite-bowser/issues/184
btw not going to fix the typo with my branch name.
> Pass through useYarn to react-native-cli

- boilerplate/app/i18n/en.json
- boilerplate/app/screens/second-example-screen/second-example-screen.tsx.ejs
Resolves #178
Cleans up some ejs formatting issues on the second example screen.
> Add hint regarding reactotron demo

- boilerplate/app/components/screen/screen.presets.ts
- boilerplate/app/components/screen/screen.props.ts
- boilerplate/app/components/screen/screen.tsx
- boilerplate/app/i18n/en.json
- boilerplate/app/screens/first-example-screen/first-example-screen.tsx.ejs
- boilerplate/app/screens/second-example-screen/second-example-screen.tsx.ejs
- commands/generate/screen.js
- templates/screen.ejs
* Adds SafeAreaView to Screen component (resolves #97)
* Adds KeyboardAvoidingView to Screen component
* Adds StatusBar to Screen component
* Adds `unsafe`, `statusBar`, and `keyboardOffset` props to Screen component to control above
* Reduces presets to `"fixed"` and `"scroll"` corresponding to `"fixedStack"` and `"scrollStack"` since in practice we always used the stack presets and they're the alignment behavior is overridable via the `style` prop anyway.
* Updates existing examples screen to reflect above preset change
* Updates screen generator to reflect preset change and fix #180
> Update Screen Component

- boilerplate/app/utils/storage/storage.test.ts
- boilerplate/app/utils/storage/storage.ts
- boilerplate/package.json.ejs
- boilerplate/test/mock-async-storage.ts
- boilerplate/test/setup.ts
* Updates to use community managed AsyncStorage (resolves #190)
* Will still have a yellowbox warning until https://github.com/infinitered/reactotron-react-native/issues/14 is resolved
> Update to community managed AsyncStorage

- .circleci/config.yml
- boilerplate.js
- boilerplate/README.md
- boilerplate/ignite.json.ejs
- commands/generate/navigator.js
- package.json
- readme.md
This is paired with https://github.com/infinitered/ignite/pull/1415.
> Delegate git init and ignite attach to Ignite CLI

- boilerplate/app/app.tsx.ejs
- boilerplate/app/models/environment.ts
- boilerplate/app/models/root-store/setup-root-store.ts
- boilerplate/e2e/firstTest.spec.js
- boilerplate/e2e/init.js
- test/generators-integration.test.js
1. Made wiring of the other stores automatic, I did not even realized other stores are not automatically wired unless you specify it again on app.tsx. use spread operator to do it
2. Instead of editing two files when adding new api, just put the setup on the Environment class
3. ran eslint auto fixes
> Minor template syntax fix

- boilerplate/package.json.ejs
> fix: missing dependency

- boilerplate/package.json.ejs
Encountered issues with Detox 12.x to run app and accept permissions. Bumping the version did solve the issue and did not break anything for me.
Anyone else can confirm and merge ?
> 📦Bump detox to 14.0.1

- readme.md
Hi.
Thought it would be good to have some resources regarding upgrading in the readme. 
Yes, I know I'm "plugging" ignite-bowser-diff-purge, but hey it might help someone, so why not.
> Added block in readme regarding upgrading

- readme.md
Added a link to Frank's React Native 3-part series as well as Gary Bernhardt's free TypeScript course.
> Added link to setup React Native & a TypeScript course

- commands/generate/navigator.js
> fix: await usage for ask

- readme.md
> Add Jamon's talk to README

- readme.md
> Text touchups

- boilerplate/app/app.tsx.ejs
- boilerplate/package.json.ejs
Added react-native-screen
@jamonholmgren please review and tell if anything is wrong.
This PR refers to #269
> add react-native-screen

- boilerplate/app/screens/demo-screen/demo-screen.tsx.ejs
Fixes #347 
Removed the double ``() =>`` from line 82 in the demo-screen.tsx
> Fixed issue navigation.goBack() not working

- readme.md
This version of the video has better audio than the nearly inaudible previous version.
> Update live coding demo link in README.md

- boilerplate/app/components/switch/switch.tsx
- boilerplate/app/navigation/navigation-utilities.tsx
- boilerplate/app/services/reactotron/reactotron.ts.ejs
- boilerplate/package.json.ejs
Include `eslint-plugin-react-hooks`.
> Fix #274 - Add eslint-plugin-react-hooks

- tsconfig.json
Closes #201 
* Update bowser's tsconfig.json settings to match [this commit.](https://github.com/jamonholmgren/PlayerPopularity/compare/dc6facfe5faa8f28ef2875e1f916d37417bb3c40..master#diff-e5e546dd2eb0351f813d63d1b39dbc48)
> Update tsconfig settings

- boilerplate/package.json.ejs
Fixes https://github.com/infinitered/ignite-bowser/issues/377!
Updates to latest detox and uses updated commands. The old ones don't seem to work anymore.
> chore(boilerplate): upgrade detox and update detox commands
